version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
    
  hbase:
    image: harisekhon/hbase
    container_name: hbase
    ports:
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 16040:16040
      - 16060:16060
      - 16070:16070
    environment:
      - HBASE_MANAGES_ZK=true
    links:
      - zookeeper
    depends_on:
      - zookeeper

