version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_tp1
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka_tp1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "sensordatainputfrancois:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  hbase:
    image: harisekhon/hbase
    ports:
      - 8080:8080
      - 8085:8085
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
    environment:
      - HBASE_MANAGES_ZK=true